### ISSUE TITLE
Run iOS example error

### ISSUE THREAD

**Issue by cabelin** [oijusti/react-native-firebaseui-auth#1]
Hi, i want to use this lib, but when i try to run example in iOS i can't
I follow steps in README.md but i catch this error: "Module 'FBSDKCoreKit' not found".

Do exists any additional step not listeted on the README.md?

**Comment by oijusti** [comment]
> Hi, i want to use this lib, but when i try to run example in iOS i can't
> I follow steps in README.md but i catch this error: "Module 'FBSDKCoreKit' not found".
> 
> Do exists any additional step not listeted on the README.md?

**Try this:**
1. Navigate to `../ios/Pods/FBSDKLoginKit/FBSDKLoginKit/FBSDKLoginKit/` 
2. Open `FBSDKLoginButton.h`
3. Find this if-else code:

    ```Objective-C
    #if defined BUCK || defined FBSDKCOCOAPODS || defined __cplusplus
    #import <FBSDKCoreKit/FBSDKCoreKit.h>
    #else
    @import FBSDKCoreKit;
    #endif
    ```
4. Comment it all but the line`#import <FBSDKCoreKit/FBSDKCoreKit.h>`
5. Make sure it looks like this: 

    ![FIX](https://user-images.githubusercontent.com/15204182/86058923-4efe4900-ba27-11ea-9645-67e6a255780f.png)
6. Clean and Build

**Comment by cabelin** [comment]
I found another solution here: https://github.com/facebook/facebook-ios-sdk/issues/1102#issuecomment-551872120
But i tested your solution and it worked too

Thanks

**Comment by oijusti** [comment]
> 
> 
> I found another solution here: [facebook/facebook-ios-sdk#1102 (comment)](https://github.com/facebook/facebook-ios-sdk/issues/1102#issuecomment-551872120)
> But i tested your solution and it worked too
> 
> Thanks

Awesome! You're welcome
