### ISSUE TITLE
No Apple auth

### ISSUE THREAD

**Issue by achuinard** [oijusti/react-native-firebaseui-auth#2]
Great project. I see it doesn't support Apple sign-in though. I may open a PR for this with the fixes but wanted to first file an issue.

**Comment by achuinard** [comment]
See pull #3

**Comment by oijusti** [comment]
> See pull #3

Thanks, I will have a look!

**Comment by achuinard** [comment]
Also I sent you a few PayPal $, hope you received them.

**Comment by oijusti** [comment]
@achuinard Thanks for your support! 

Great job! I approved the PR.
