### ISSUE TITLE
Option to only allow sign in, not sign up?

### ISSUE THREAD

**Issue by fabyeah** [oijusti/react-native-firebaseui-auth#22]
Thanks for this package!
Is it possible to allow only sign in, but not sign up?  Or is there any way to achieve this with this package?

**Comment by fabyeah** [comment]
And also is there any way to customize the sign up form? I don't necessarily want to ask for first and last name, but rather a username or nothing at all instead.

**Comment by oijusti** [comment]
Hey @fabyeah, let me check that.

**Comment by oijusti** [comment]
Hi @fabyeah, 

When you call _signIn_ the returned value _isNewUser_ indicates whether or not the current user was signed in for the first time. Not sure if that helps you to achieve what you are looking for.

Regarding to the second part, I did not find such kind of customization in the docs, this is what you can do in both platforms,
https://github.com/firebase/FirebaseUI-Android/blob/master/auth/README.md#ui-customization
https://github.com/firebase/FirebaseUI-iOS/blob/master/Auth/README.md#custom-sign-in-screen

**Comment by oijusti** [comment]
Hi @fabyeah, finally customization is available https://github.com/oijusti/react-native-firebaseui-auth#ui-customization

**Comment by fabyeah** [comment]
@oijusti Thanks for following up. Comparing with the FirebaseUI-Android implementation, what I'm looking for are these two features:

- https://github.com/firebase/FirebaseUI-Android/issues/1410
- https://github.com/koji-1009/flutter_auth_ui/issues/19

Can this be achieved with this package?

**Comment by oijusti** [comment]
@fabyeah It looks achievable, let me take a look at that!

**Comment by oijusti** [comment]
@fabyeah this functionality is available now https://github.com/oijusti/react-native-firebaseui-auth#email-password-settings

**Comment by fabyeah** [comment]
@oijusti `requireDisplayName` works nicely 👍 
`allowNewEmailAccounts` also works great for email/password signup, but users can still create new accounts when using the Google signin 😟 . Not sure if this was your intention. As I'm using both email/password and Google auth, I'd love it if it can be disabled for that, too. I'm not sure, but it might be possible to disable it like described here: https://github.com/firebase/FirebaseUI-Android/issues/1410#issuecomment-412715410 with the `setAllowNewAccounts(false)`.
As linked in the following issue: https://github.com/firebase/FirebaseUI-Android/issues/530#issuecomment-487305676

**Comment by oijusti** [comment]
hi @fabyeah, for my understanding it only works for email/pass auth.
