### ISSUE TITLE
Can't sign in with Google

### ISSUE THREAD

**Issue by fabyeah** [oijusti/react-native-firebaseui-auth#23]
Email sign in works, but when I try to sign in with Google, I'm getting a toast "Code: 10, Message: 10:" and nothing happens.

**Comment by fabyeah** [comment]
Google Sign in from the web app (using firebaseui-react) works, so the Firebase/Google setup should be correct.

**Comment by oijusti** [comment]
Hi @fabyeah, the issue is with android or iOS?

**Comment by fabyeah** [comment]
@oijusti I tested it with android device

**Comment by fabyeah** [comment]
It works on iOS.

To make it work on android, it seems like one has to add "SHA certificate fingerprints" to the Android App in the Firebase console project settings.

- https://stackoverflow.com/questions/51314476/firebase-auth-ui-google-sign-in-code10-message10
- https://stackoverflow.com/questions/51360250/firebase-ui-authentication-with-google-fails-with-message-code10-message10/51360406
- https://stackoverflow.com/questions/60049668/how-to-solve-code-10-message-10-with-google-signing-option

Kind of cumbersome if you just want to play around and test an app locally without uploading it to Google Play... 🙁

**Comment by oijusti** [comment]
Good catch!

**Comment by fabyeah** [comment]
Just for posterity: I actually had the wrong SHA1 set in Firebase. So if you encounter this error, make sure you get the SHA1 from the `debug.keystore` in your project's `android/app` folder, NOT from some rogue `debug.keystore` for example in `/Users/<username>/.android/debug.keystore`. You can use `keytool -keystore debug.keystore -list -v` in the project's `android/app` folder to get the SHA1.

So for development you probably only need that one SHA1 (haven't tried it).
