### ISSUE TITLE
Change background

### ISSUE THREAD

**Issue by Saulenco** [oijusti/react-native-firebaseui-auth#24]
Hi, thanks for module! It will be nice if there in config will be some UI configs such as background Image , color, something like that

**Comment by oijusti** [comment]
Hi @Saulenco, thanks, this is a great idea. Lately, I have not had much time to work on it, I hope I can add this new feature soon.

**Comment by oijusti** [comment]
Hi @Saulenco, finally customization is available https://github.com/oijusti/react-native-firebaseui-auth#ui-customization

**Comment by Saulenco** [comment]
Hi @oijusti i see that only the android has the support for background and logo, it is possible to add for iOS also ?

**Comment by oijusti** [comment]
hi @Saulenco, right now for iOS the only way to do it is editing the _FUICustomAuthPickerViewController.xib_ file directly from XCode. You can change the background and add the logo using the tools that XCode provide.
