### ISSUE TITLE
Working with latest FirebaseUI pod?

### ISSUE THREAD

**Issue by achuinard** [oijusti/react-native-firebaseui-auth#33]
I'm using FirebaseUI 12 and get this error when trying to run my React Native app:

```FirebaseUI/FirebaseEmailAuthUI.h' file not found```

#import <FirebaseUI/FirebaseEmailAuthUI.h>

Does this work with the latest FirebaseUI pod?

**Comment by oijusti** [comment]
Hi, it has been tested in the version 10. But not in the 12. I will have a look at it, thanks!

**Comment by oijusti** [comment]
Done, Please upgrade to version 1.2.22!

**Comment by achuinard** [comment]
You are amazing. Thank you!
