### ISSUE TITLE
Can't build app

### ISSUE THREAD

**Issue by michaelst** [oijusti/react-native-firebaseui-auth#35]
I'm not sure what else would help debug this, but here is a screenshot of the error log

<img width="1131" alt="image" src="https://user-images.githubusercontent.com/4080508/131932272-bde109cd-e88a-4a16-9720-9f4977e6e20a.png">

**Comment by oijusti** [comment]
hi @michaelst, 
Are you still having building issues? if not, how did you solve them?

**Comment by michaelst** [comment]
I ended up going a different route
