### ISSUE TITLE
'FirebaseUI/FirebaseUI.h' file not found

### ISSUE THREAD

**Issue by Saulenco** [oijusti/react-native-firebaseui-auth#38]
after npm install, and pod install i getting  this error also the `library not found for -lFBSDKLoginKit`
![Screenshot 2021-11-22 at 10 12 43](https://user-images.githubusercontent.com/8323284/142825953-3c52b06b-e70d-4b3a-87f9-7a8121fbfef5.png)

i have added to my podFile
```
  pod 'FirebaseUI'
  pod 'FBSDKCoreKit', :modular_headers => true
```

and after pod install the frameworks are installed

```
Installing FirebaseUI (4.1.1)
Installing FBSDKCoreKit 12.1.0
```

but there are not visible in my project.

i have removed all modules and package-lock, pods and reinstall it again, but no success.
What should i do next to make it work?

**Comment by oijusti** [comment]
Hi, let me try to replicate this error...

**Comment by oijusti** [comment]
Hey @Saulenco, did you solve this issue?
I see you have an old version of FirebaseUI (4.1.1). 
The example in this repo uses the following versions, so it should work if you can install them.

```
pod 'Firebase/Analytics', '~>8.6.0'
pod 'FirebaseUI', '~>12.0.2'
pod 'FBSDKCoreKit', '~>11.2.1', :modular_headers => true
```

**Comment by fabyeah** [comment]
@Saulenco were you able to solve this? I have a similar problem #55
