### ISSUE TITLE
M1 issues?

### ISSUE THREAD

**Issue by achuinard** [oijusti/react-native-firebaseui-auth#56]
I'm getting a strange error trying to use this on my new M1 Mac.

```
node_modules/react-native-firebaseui-auth/ios/RNFirebaseuiAuth.m normal arm64 objective-c com.apple.compilers.llvm.clang.1_0.compiler (in target 'react-native-firebaseui-auth' from project 'Pods')
```

Did I do something wrong?

**Comment by achuinard** [comment]
Thanks for getting back to me - I'll try again soon with your latest updates.

**Comment by achuinard** [comment]
It seems to be working well. Thank you so much for this library!

One consideration is that you may be able just put specific FirebaseUI pods in your Podfile. The "FirebaseUI" pod brought in a lot of dependencies. I believe you can instead do something like "FirebaseUI/Email", if you're just supporting email auth for example.

**Comment by oijusti** [comment]
> It seems to be working well. Thank you so much for this library!
> 
> One consideration is that you may be able just put specific FirebaseUI pods in your Podfile. The "FirebaseUI" pod brought in a lot of dependencies. I believe you can instead do something like "FirebaseUI/Email", if you're just supporting email auth for example.

Makes sense, thanks for the insights!
