### ISSUE TITLE
Pass isNewUser?

### ISSUE THREAD

**Issue by achuinard** [oijusti/react-native-firebaseui-auth#7]
I know on the Android side on the FirebaseUI Auth activity result you can check if the user was a new signup or not. Are you able to do that somehow with iOS? I don't know if the same API is supported but if so it would be nice to pass that data through to the callback so I can do something special in my app if the sign-in created a new user.

**Comment by oijusti** [comment]
> I know on the Android side on the FirebaseUI Auth activity result you can check if the user was a new signup or not. Are you able to do that somehow with iOS? I don't know if the same API is supported but if so it would be nice to pass that data through to the callback so I can do something special in my app if the sign-in created a new user.

That is a great idea, let me check please

**Comment by oijusti** [comment]
> I know on the Android side on the FirebaseUI Auth activity result you can check if the user was a new signup or not. Are you able to do that somehow with iOS? I don't know if the same API is supported but if so it would be nice to pass that data through to the callback so I can do something special in my app if the sign-in created a new user.

@achuinard  Done! please check the readme and let me know.

**Comment by achuinard** [comment]
@oijusti You are a legend, thank you. I'll add this into my project and let you know how it goes.

**Comment by oijusti** [comment]
@achuinard My pleasure

**Comment by achuinard** [comment]
It worked really well, the only thing that tripped me up just a little was that IntelliJ thought these properties existed on the return object but they don't:

![image](https://user-images.githubusercontent.com/469647/90358554-fb1de280-e01b-11ea-90c9-52ab6fa4c7f3.png)

The uid, email, and isNewUser property are all directly accessible on the returned object. Perhaps the typings for this need to be updated?

**Comment by oijusti** [comment]
@achuinard , yes, It needs to be completed. Thanks for reminding me of this 😃

**Comment by oijusti** [comment]
@achuinard I added some types if you want to give it a try
