### ISSUE TITLE
Should facebook Android SDK version be bumped up?

### ISSUE THREAD

**Issue by yonghongren** [oijusti/react-native-firebaseui-auth#9]
After integrating Facebook auth for Android, Facebook developer console gives a warning that SDK needs to be upgraded. Following change gets rid of the warning:

```
--- node_modules/react-native-firebaseui-auth/android/build.gradle-orig	2020-08-13 16:31:42.000000000 -0400
+++ node_modules/react-native-firebaseui-auth/android/build.gradle	2020-08-13 16:31:52.000000000 -0400
@@ -49,7 +49,7 @@
 
     // Required only if Facebook login support is required
     // Find the latest Facebook SDK releases here: https://goo.gl/Ce5L94
-    implementation 'com.facebook.android:facebook-android-sdk:4.+'
+    implementation 'com.facebook.android:facebook-android-sdk:[5,6]'
 
     // Required only if Twitter login support is required
     // Find the latest Twitter SDK releases here: https://goo.gl/E5wZvQ
```

Are there reasons not to make this change?

**Comment by oijusti** [comment]
hey @yonghongren I have not tested that sdk version. 
I will check it soon.
Tks.

**Comment by yonghongren** [comment]
@oijusti, Thanks for the reply. FYI, I am using the newer version and I haven't seen issues so far. Would love to know if you observe anything to the contrary. Thanks.

**Comment by oijusti** [comment]
@yonghongren Thanks for the information. I will let you know if I find any issue with it.

**Comment by oijusti** [comment]
@yonghongren I implemented your suggestion and it is working smoothly. 
Please upgrade to the last version and let me know.
Thanks!
